export const ActionTypes = {
  //Login Action type
  LOGIN_REQUEST: "LOGIN_REQUEST",

  //Register Action Type
  ADD_USER: "ADD_USER",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAIL: "REGISTER_FAIL",
  FORM_SUBMITION_STATUS: "FORM_SUBMITION_STATUS",

  //Product Action Type
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCTS: "DELETE_PRODUCTS",
  REMOVE_SELECTED_PRODUCTS: "REMOVE_SELECTED_PRODUCTS",

  //Message Action Type
  SET_MESSAGE: "SET_MESSAGE",
  CLEAR_MESSAGE: "CLEAR_MESSAGE",
};
